name: Push image

on:
  pull_request:
    branches:
      - main
    types: [ closed ]

permissions:
  id-token: write
  contents: read

jobs:
  buildx:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.CONTAINER_REGISTRY_PATH }}/githubactions-test
      IMAGE_TAG: ${{ github.sha }}
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: deploy-role-session
          aws-region: ap-northeast-1
      - run: aws sts get-caller-identity
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
